### ISSUE TITLE
Unable to change REST API URL

### ISSUE THREAD

**Issue by b-mueller** [wbobeirne/joule-extension#162] opened 2019-02-13 13:46 UTC
### Description of the Issue

Changing the REST API URL in Settings doesn't appear to have any effect.

I initially set the REST URL to a remote IP of a node running in my LAN. The node is now running on a different IP, but Joule's UI doesn't allow me to update from the original one.

### Steps to Reproduce

Set an API  invalid URL, e.g.:

![screen shot 2019-02-13 at 20 37 23](https://user-images.githubusercontent.com/5194767/52715808-f95f0300-2fcf-11e9-99e6-102b7c0f5562.png)

Change to the correct URL and click "Connect":

![screen shot 2019-02-13 at 20 43 43](https://user-images.githubusercontent.com/5194767/52715871-18f62b80-2fd0-11e9-8d4b-45c5632562c5.png)

Re-opening settings still shows the old URL:

![screen shot 2019-02-13 at 20 44 22](https://user-images.githubusercontent.com/5194767/52715905-30cdaf80-2fd0-11e9-87a0-45cd3596721f.png)

### Description of Your Setup

*Browser & version*: Chome Version 72.0.3626.96 (Official Build) (64-bit)
*Operating system*: macOS Mojave
*Node software & version*: Joule 0.4.0

### Console Logs / Screenshots

See above.

**Comment by b-mueller** [comment] 2019-02-13 13:48
I also noted that a password dialog pops up very briefly, not sure if that's relevant...

**Comment by jamaljsr** [comment] 2019-02-15 07:40
This is strange. Can you open the Chrome Developer Tools console. Right-click on the background in Joule and click on `Inspect`. Then click the 'Console' tab in the window that opens, then reproduce the problem. Can you share a screenshot of the console logs?

**Comment by groundstart** [comment] 2019-02-15 22:33
Similar issue here. Joule was working previously, but recently stopped connecting. Field is prefilled with https://localhost:8080, which errors. Then tried URL which Node Launcher copies: https://127.0.0.1:8080 which also errors. Per attached.
<img width="1339" alt="screen shot 2019-02-15 at 4 10 10 pm" src="https://user-images.githubusercontent.com/23239196/52887942-5d540980-313f-11e9-8cb6-7d8d8afd57f4.png">

**Comment by wbobeirne** [comment] 2019-02-16 02:15
@groundstart that's unrelate to this issue. You will need to add the SSL cert as trusted. You can either follow the instructions in the error message to temporarily fix, or you can search for a guide based on your operating system on how to add a self-signed SSL cert.

**Comment by b-mueller** [comment] 2019-02-16 11:42
Ok, at the moment I tried to reproduce this and take a screen recording, it suddenly worked & not I can't reproduce it anymore 😅
The problem appears to be that the password dialog would pop up and close immediately, perhaps because of some event being triggered, but now it's working as expected. I'll close this issue for now and re-open if it pops up again / I can properly reproduce it.

**Comment by b-mueller** [comment] 2019-02-16 11:55
Ok, this is funny. It still happens but **only when the developer console is closed**.  When I have the console open everything works as expected. Which is super frustrating because it means that I can't get any debugging output.

Best I could do was make a [screen recording](https://www.dropbox.com/s/a8a7mgj9l8garuz/changing-url.mov?dl=0).

**Comment by jamaljsr** [comment] 2019-02-16 16:59
Oh these videos are very helpful. Thanks for sharing. I can’t think of any reason why Joule would close automatically when prompting for the password.

Here’s two things I’d like for you to do to try to troubleshoot:

1. Test to see the behavior if the password was already entered. From the home screen, click on the Deposit button then enter your password. Now try to reproduce the issue. What happens?

2. Test to see if the full page behaves differently. Click on the 3-bars menu (top-right) then click on Full Page. In the new tab that opens, reproduce the issue with the console opened & closed. What happens?

My gut is telling me that your data in browser storage may be corrupted, but I could be wrong. Resetting your connection data from the Settings screen should fix it if this is the case.

**Comment by b-mueller** [comment] 2019-02-17 05:02
Results:

1. Whether the wallet is locked or not doesn't affect the outcome.

2. In full page mode, changing the URL *never* works for me, even when the console is open. [No output on the console :(](https://www.dropbox.com/s/dt0qaklynedgf5m/joule3.mov?dl=0). 

3. The only way I can change the REST Url is in windows mode with the developer console open.

> Resetting your connection data from the Settings screen should fix it if this is the case.

Keeping the developer console open was a viable workaround for me.

**Comment by jamaljsr** [comment] 2019-02-17 05:21
Sorry, one last thing. In the full page mode, can you try to edit the url in the full page tab, instead of the toolbar icon popup? I'm really curious what's going on here.

**Comment by b-mueller** [comment] 2019-02-17 06:09
> Can you try to edit the url in the full page tab, instead of the toolbar icon popup?

Yep, that works as expected!

**Comment by b-mueller** [comment] 2019-02-17 06:11
I don't know if that helps but I encountered a very similar issue in Metamask recently. In that case it was cause by a polling loop. See [here](https://github.com/clovers-network/clovers-dapp/issues/196) and [here](https://github.com/MetaMask/metamask-extension/issues/5814).

**Comment by wbobeirne** [comment] 2019-03-20 17:52
Hmm, hard to see where those might be related. Since you were able to work around, and we couldn't reproduce, I'm going to close this issue. Let me know if it happens again and you uncover any details!

**Closed by wbobeirne** 2019-03-20 17:52 UTC
